# Generated by Django 4.1.1 on 2022-09-07 05:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('thumbnail', models.ImageField(upload_to='images_recipes/')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
